# -----------------------------------------------------------------------------
# frigate_config.yml - Frigate Configuration Placeholder
# This file needs to be fully configured with your camera streams.
# -----------------------------------------------------------------------------
# Use this as a starting point.
# NOTE: This file is mounted as ./frigate_config.yml in the compose file.

mqtt:
  # The host is the name of the mosquitto service in the Podman network
  host: mosquitto
  user: ${MQTT_USER} # Use the variable defined in secrets.yml
  password: ${MQTT_PASSWORD} # Use the variable defined in secrets.yml

# This detector uses the CPU since you are not using a Coral USB
detectors:
  cpu1:
    type: cpu

# Define your camera streams here
cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://camera_user:camera_pass@192.168.1.100/stream # Update with your camera URL
          roles:
            - detect
            - record
    detect:
      # Only detect 'person' by default to save CPU
      enabled: True
      objects:
        - person
    record:
      enabled: True
